In [1]:
import pandas as pd
import numpy as np
import glob

In [2]:
columns_to_load = ["period","reporterISO", "reporterDesc", "flowCode","partnerDesc","partnerISO", "cmdCode", "H5","cifvalue", "fobvalue"]

In [3]:
root_folder = "/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5"
file_pattern = root_folder + "/*.csv"
files = glob.glob(file_pattern)
# Check matched files
print(files)

['/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_1.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_10.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_100.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_11.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_12.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_13.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_14.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_15.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_16.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_17.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_18.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_19.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_2.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_20.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_21.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_22.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_23.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_24.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_25.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_26.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_27.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_28.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_29.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_3.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_30.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_31.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_32.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_33.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_34.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_35.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_36.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_37.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_38.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_39.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_4.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_40.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_41.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_42.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_43.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_44.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_45.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_46.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_47.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_48.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_49.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_5.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_50.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_51.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_52.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_53.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_54.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_55.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_56.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_57.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_58.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_59.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_6.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_60.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_61.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_62.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_63.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_64.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_65.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_66.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_67.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_68.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_69.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_7.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_70.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_71.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_72.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_73.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_74.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_75.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_76.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_77.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_78.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_79.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_8.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_80.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_81.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_82.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_83.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_84.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_85.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_86.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_87.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_88.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_89.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_9.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_90.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_91.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_92.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_93.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_94.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_95.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_96.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_97.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_98.csv', '/content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_99.csv']

In [4]:
dataframes = []
i=0

In [5]:
for file in files:
    i+=1
    print(f"Loading {file}...")
    # Read the CSV file with specified columns
    df_chunk = pd.read_csv(file, usecols=columns_to_load)
    # Append the resulting DataFrame to the list
    dataframes.append(df_chunk)

Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_1.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_10.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_100.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_11.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_12.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_13.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_14.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_15.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_16.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_17.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_18.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_19.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_2.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_20.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_21.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_22.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_23.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_24.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_25.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_26.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_27.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_28.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_29.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_3.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_30.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_31.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_32.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_33.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_34.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_35.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_36.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_37.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_38.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_39.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_4.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_40.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_41.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_42.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_43.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_44.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_45.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_46.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_47.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_48.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_49.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_5.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_50.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_51.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_52.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_53.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_54.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_55.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_56.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_57.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_58.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_59.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_6.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_60.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_61.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_62.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_63.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_64.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_65.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_66.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_67.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_68.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_69.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_7.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_70.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_71.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_72.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_73.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_74.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_75.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_76.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_77.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_78.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_79.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_8.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_80.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_81.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_82.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_83.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_84.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_85.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_86.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_87.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_88.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_89.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_9.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_90.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_91.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_92.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_93.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_94.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_95.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_96.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_97.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_98.csv...
Loading /content/drive/MyDrive/Auto Research Team Folder/UNCOMTRADE Data/HS 6 DIGIT/2022/Converted To 2017 H5/combined_file_99.csv...

In [6]:
final_df_2022 = pd.concat(dataframes, ignore_index=True)

In [8]:
final_df_2022.shape[0]

18140538

In [9]:
final_df_2022.head()

,period,reporterISO,reporterDesc,flowCode,partnerISO,partnerDesc,cmdCode,cifvalue,fobvalue,H5
0,2022,AND,Andorra,M,W00,World,10121,1261.942,NaN,10121
1,2022,AND,Andorra,M,FRA,France,10121,1261.942,NaN,10121
2,2022,AGO,Angola,M,W00,World,10121,61772.167,6693.503,10121
3,2022,AGO,Angola,M,ARG,Argentina,10121,4824.369,168.227,10121
4,2022,AGO,Angola,M,FRA,France,10121,2279.887,47.493,10121

In [15]:
print(final_df_2022['cifvalue'].sum())
print(final_df_2022['fobvalue'].sum())

46072473365449.36
58976057972105.48

In [16]:
# Replace non-finite values with a suitable integer (e.g., -1) before conversion
final_df_2022['H5'] = pd.to_numeric(final_df_2022['H5'], errors='coerce').fillna(-1).astype(int)

In [17]:
final_df_2022['H5'] = final_df_2022['H5'].astype(str).str.zfill(6)  # Pad with leading zeros
final_df_2022['cmdCode'] = final_df_2022['cmdCode'].astype(str).str.zfill(6)  # Pad with leading zeros

In [18]:
final_df_2022.sort_values(by='cmdCode', ascending=True, inplace=True)

In [19]:
final_df_2022.head()

,period,reporterISO,reporterDesc,flowCode,partnerISO,partnerDesc,cmdCode,cifvalue,fobvalue,H5
0,2022,AND,Andorra,M,W00,World,010121,1261.942,NaN,010121
3620,2022,SVK,Slovakia,M,_X,"Areas, nes",010121,4212.195,4184.815,010121
3621,2022,SVN,Slovenia,M,W00,World,010121,254216.109,NaN,010121
3622,2022,SVN,Slovenia,M,BEL,Belgium,010121,88343.920,NaN,010121
3623,2022,SVN,Slovenia,M,FRA,France,010121,59058.565,NaN,010121

In [20]:
flow_codes = final_df_2022['flowCode'].unique()
split_dfs = {}
# Iterate through unique flow codes and split the DataFrame
for flow_code in flow_codes:
  split_dfs[flow_code] = final_df_2022[final_df_2022['flowCode'] == flow_code]

split dataframes based of flowcode

In [21]:
import_df = split_dfs['M']
export_df = split_dfs['X']

In [22]:
import_df = import_df[import_df.partnerDesc != 'World']
export_df = export_df[export_df.partnerDesc != 'World']

In [23]:
import_df.reset_index(drop=True, inplace=True)
export_df.reset_index(drop=True, inplace=True)

In [24]:
import_df.sample(n=5)

,period,reporterISO,reporterDesc,flowCode,partnerISO,partnerDesc,cmdCode,cifvalue,fobvalue,H5
3237550,2022,BLZ,Belize,M,PAN,Panama,540784,1.291225e+03,NaN,540784
3231172,2022,VNM,Viet Nam,M,S19,"Other Asia, nes",540772,1.938277e+07,NaN,540772
2231834,2022,ITA,Italy,M,SRB,Serbia,392113,4.258842e+06,NaN,392113
7209524,2022,HUN,Hungary,M,BEL,Belgium,851718,1.767830e+05,NaN,851718
5318066,2022,EST,Estonia,M,E19,"Other Europe, nes",740329,1.449790e+03,NaN,740329

In [25]:
export_df.sample(n=5)

,period,reporterISO,reporterDesc,flowCode,partnerISO,partnerDesc,cmdCode,cifvalue,fobvalue,H5
163475,2022,BHR,Bahrain,X,LBR,Liberia,040690,NaN,55.000,040690
1740260,2022,SGP,Singapore,X,SEN,Senegal,350699,NaN,65.280,350699
1648572,2022,CZE,Czechia,X,KAZ,Kazakhstan,340111,NaN,221.000,340111
2139222,2022,DNK,Denmark,X,GRL,Greenland,392330,NaN,335997.712,392330
6292328,2022,IND,India,X,SEN,Senegal,848390,NaN,251312.950,848390

In [28]:
gambia = export_df[export_df['reporterDesc'] == 'Gambia']
print(gambia['fobvalue'].sum())
gambia

54912295.791999996

,period,reporterISO,reporterDesc,flowCode,partnerISO,partnerDesc,cmdCode,cifvalue,fobvalue,H5
52774,2022,GMB,Gambia,X,KOR,Rep. of Korea,030191,NaN,48074.852,030191
57084,2022,GMB,Gambia,X,TGO,Togo,030229,NaN,58201.304,030229
57090,2022,GMB,Gambia,X,ESP,Spain,030229,NaN,30049.349,030229
57091,2022,GMB,Gambia,X,KOR,Rep. of Korea,030229,NaN,183051.728,030229
57379,2022,GMB,Gambia,X,KOR,Rep. of Korea,030231,NaN,33921.744,030231
...,...,...,...,...,...,...,...,...,...,...
7867182,2022,GMB,Gambia,X,GBR,United Kingdom,940360,NaN,516.658,940360
7902491,2022,GMB,Gambia,X,GBR,United Kingdom,940430,NaN,328.444,940430
8062909,2022,GMB,Gambia,X,CUB,Cuba,960500,NaN,12088.544,960500
8172906,2022,GMB,Gambia,X,MLI,Mali,999999,NaN,2035.804,999999
8172907,2022,GMB,Gambia,X,CHN,China,999999,NaN,35976.349,999999

In [ ]:
cifvalue_sum = import_df['cifvalue'].sum()
print(f"The sum of cifvalue is: {cifvalue_sum}")

The sum of cifvalue is: 23036393153667.797

In [ ]:
fobvalue_sum = export_df['fobvalue'].sum()
print(f"The sum of fobvalue is: {fobvalue_sum}")

The sum of fobvalue is: 23057408680394.03

In [ ]:
import_df = import_df.drop(columns=['fobvalue', 'flowCode'])
export_df = export_df.drop(columns=['cifvalue', 'flowCode'])

In [ ]:
export_df = export_df.rename(columns={'reporterISO':'exporterISO','reporterDesc':'exporter','partnerISO':'importerISO','partnerDesc':'importer','fobvalue': 'export_value'})
import_df = import_df.rename(columns={'reporterISO': 'importerISO','reporterDesc':'importer','partnerISO':'exporterISO','partnerDesc':'exporter','cifvalue': 'import_value'})

In [ ]:
import_df.head()

,period,importerISO,importer,exporterISO,exporter,cmdCode,import_value,H5
0,2022,AND,Andorra,FRA,France,010121,1261.942,010121
1,2022,AGO,Angola,ARG,Argentina,010121,4824.369,010121
2,2022,AGO,Angola,FRA,France,010121,2279.887,010121
3,2022,AGO,Angola,NAM,Namibia,010121,4404.622,010121
4,2022,AGO,Angola,PRT,Portugal,010121,276.717,010121

In [ ]:
export_df.head()

,period,exporterISO,exporter,importerISO,importer,cmdCode,export_value,H5
0,2022,AGO,Angola,BRA,Brazil,010121,423.390,010121
1,2022,AGO,Angola,COD,Dem. Rep. of the Congo,010121,5210.594,010121
2,2022,AGO,Angola,MOZ,Mozambique,010121,58.037,010121
3,2022,ARG,Argentina,BRA,Brazil,010121,171000.000,010121
4,2022,ARG,Argentina,CHL,Chile,010121,19300.000,010121

merge imports and exports data

In [ ]:
trade_data = pd.merge(import_df, export_df, on=['period','exporter','exporterISO','cmdCode', 'importer','importerISO',  'H5'], how='outer')
print(trade_data.shape)
trade_data.head()

(11983800, 9)

,period,importerISO,importer,exporterISO,exporter,cmdCode,import_value,H5,export_value
0,2022,ARE,United Arab Emirates,AFG,Afghanistan,010121,8300.340,010121,NaN
1,2022,ARE,United Arab Emirates,AFG,Afghanistan,010129,1.089,010129,NaN
2,2022,UZB,Uzbekistan,AFG,Afghanistan,010129,8500.000,010129,NaN
3,2022,ARE,United Arab Emirates,AFG,Afghanistan,010190,2.995,010190,NaN
4,2022,IRN,Iran,AFG,Afghanistan,010221,32579.000,010221,NaN

In [ ]:
trade_data.isna().sum()

period                0
importerISO           0
importer              0
exporterISO           0
exporter              0
cmdCode               0
import_value    3402930
H5                    0
export_value    3810522
dtype: int64

In [ ]:
print(trade_data['cmdCode'].nunique())
print(trade_data['H5'].nunique())

5753
5385

In [ ]:
trade_data['import_value'].fillna(0, inplace=True)
trade_data['export_value'].fillna(0, inplace=True)

<ipython-input-61-f665f8bb8340>:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  trade_data['import_value'].fillna(0, inplace=True)
<ipython-input-61-f665f8bb8340>:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  trade_data['export_value'].fillna(0, inplace=True)

In [ ]:
trade_data.isna().sum()

period          0
importerISO     0
importer        0
exporterISO     0
exporter        0
cmdCode         0
import_value    0
H5              0
export_value    0
dtype: int64

In [ ]:
trade_data.head()

,period,importerISO,importer,exporterISO,exporter,cmdCode,import_value,H5,export_value
0,2022,ARE,United Arab Emirates,AFG,Afghanistan,010121,8300.0,010121,0.0
1,2022,ARE,United Arab Emirates,AFG,Afghanistan,010129,1.0,010129,0.0
2,2022,UZB,Uzbekistan,AFG,Afghanistan,010129,8500.0,010129,0.0
3,2022,ARE,United Arab Emirates,AFG,Afghanistan,010190,3.0,010190,0.0
4,2022,IRN,Iran,AFG,Afghanistan,010221,32579.0,010221,0.0

In [ ]:
print(trade_data['export_value'].sum())
print(trade_data['import_value'].sum())

23057408679226.0
23036393151705.0

In [ ]:
print(trade_data['export_value'].sum())
print(trade_data['import_value'].sum())

23057408680394.098
23036393153667.74

In [ ]:
# Round off import_value and export_value to the next whole number
trade_data['import_value'] = trade_data['import_value'].round()
trade_data['export_value'] = trade_data['export_value'].round()

In [ ]:
print(trade_data['exporter'].nunique())
print(trade_data['importer'].nunique())

In [ ]:
root_folder = "/content/drive/MyDrive/Auto Research Team Folder/Trade reconciliation/Trade  data/UN comtrade/2022"
export_name= "export_6_2022.csv"
import_name= "import_6_2022.csv"
import_df.to_csv(f'{root_folder}/{import_name}', index=False)
export_df.to_csv(f'{root_folder}/{export_name}', index=False)

In [ ]:
root_folder = "/content/drive/MyDrive/Auto Research Team Folder/Trade reconciliation/Trade  data/UN comtrade/2022"
file_name= "trade_raw_2022_H5.csv"
trade_data.to_csv(f'{root_folder}/{file_name}', index=False)

Services data

In [ ]:
services_df = pd.read_csv('/content/drive/MyDrive/Trade project data/usa_data/Commercial Services 7.31.2024.csv')

In [ ]:
services_df.head()

,FLOW,INDICATOR_CODE,REPORTER CODE,PARTNER CODE,REPORTER_COUNTRY_CODE,PARTNER_COUNTRY_CODE,REPORTING ECONOMY,PARTNER ECONOMY,SECTOR,YEAR,VALUE,UNIT
0,Imports,SOX,AFR,WL,RG950,SA000,Africa,World,Commercial services,2005,71471.11,Million US dollar
1,Exports,SOX,AFR,WL,RG950,SA000,Africa,World,Commercial services,2005,57887.48,Million US dollar
2,Exports,SOX,AL,WL,RC008,SA000,Albania,World,Commercial services,2005,1256.25,Million US dollar
3,Imports,SOX,AL,WL,RC008,SA000,Albania,World,Commercial services,2005,1317.70,Million US dollar
4,Imports,SOX,DZ,WL,RC012,SA000,Algeria,World,Commercial services,2005,4542.00,Million US dollar

In [ ]:
services_imports = services_df[services_df['FLOW'] == 'Imports']
services_exports = services_df[services_df['FLOW'] == 'Exports']

In [ ]:
services_import_2022 = services_imports[services_imports.YEAR == 2022]
services_export_2022 = services_exports[services_exports.YEAR == 2022]

In [ ]:
services_import_2022.to_csv('/content/drive/MyDrive/Trade project data/UN comtrade/2016/services_import_2016.csv', index=False)
services_export_2022.to_csv('/content/drive/MyDrive/Trade project data/UN comtrade/2016/services_export_2016.csv', index=False)

In [ ]:
#total_services = services_import_2021[services_import_2021['SECTOR'] == 'Memo item: Total services']

In [ ]:
#total_services.head()

In [ ]:
total_value = total_services['VALUE'].sum()
print(total_value)

NameError: name 'total_services' is not defined